### ISSUE TITLE
认领翻译 docs/creating-a-project.md

### ISSUE THREAD

**Issue by yanyu0517** [xcatliu/cyarnpkg.com#8]

**Comment by xcatliu** [comment]
@yanyu0517 提醒一下，你的 user.email 和 user.name 可能设置的不会，在 commits 页面链接不到你的 GitHub 账号 https://github.com/xcatliu/cyarnpkg.com/commits/master

**Comment by yanyu0517** [comment]
@xcatliu 是的，我之前用gitlab，改了user.email。我看下怎么给改回来

**Comment by xcatliu** [comment]
@yanyu0517 以前的提交改不了了，以后用新的就行 😄

**Comment by yanyu0517** [comment]
恩，我设的时候带了--global了，没注意
